### ISSUE TITLE
Aemulo更新了1.2版，能否更新tweak呢？

### ISSUE THREAD

**Issue by potpot3** [zyl0462/repo#1]
非常感谢大神写了aemulolauncher和aemulotweak，Aemulo更新了1.2版，不知道能否更新呢？

另外，能否增加功能：成功模拟后，返回桌面，再重新打开，自动给模拟就不生效了，能否修正？

谢谢你

**Comment by potpot3** [comment]
非常感谢大神写了aemulolauncher和aemulotweak，Aemulo更新了1.2版，不知道能否更新呢？

另外，能否增加功能：成功模拟后，返回桌面，再重新打开，自动给模拟就不生效了，能否修正？

谢谢你

**Comment by zyl0462** [comment]
抱歉，现在入狱了，手上暂时没设备。之前的逻辑确实是APP初始化打开自动模拟，从后台切换到前台不模拟。



***@***.***
 
发件人： potpot3
发送时间： 2022-12-11 20:18
收件人： zyl0462/repo
抄送： Subscribed
主题： Re: [zyl0462/repo] Aemulo更新了1.2版，能否更新tweak呢？ (Issue #1)
非常感谢大神写了aemulolauncher和aemulotweak，Aemulo更新了1.2版，不知道能否更新呢？
另外，能否增加功能：成功模拟后，返回桌面，再重新打开，自动给模拟就不生效了，能否修正？
谢谢你

**Comment by potpot3** [comment]
那不知道能否把这两个tweak开源呢？

我想在您的基础上更新适配Aemulo1.2版。
然后造福最新ios15系统的越狱的玩家们。


谢谢你

**Comment by zyl0462** [comment]
可以，暂时不在手上，有时间发你。
说下大概思路，
aemulolauncher，这个只要软件bundleID不变，没什么问题，可以从巨魔作者找到控制中心启动模板填上对应bundleID就可以；
aemulotweak，这个软件升级，源代码可能就没多大参考意义了，需要逆向下对应模拟的消息函数，然后把hook代码放到app进入前台对应的函数。



***@***.***
 
发件人： potpot3
发送时间： 2022-12-12 09:11
收件人： zyl0462/repo
抄送： zyl0462; Comment
主题： Re: [zyl0462/repo] Aemulo更新了1.2版，能否更新tweak呢？ (Issue #1)
那不知道能否把这两个tweak开源呢？
我想在您的基础上更新适配Aemulo1.2版。
然后造福最新ios15系统的越狱的玩家们。
谢谢你

**Comment by zyl0462** [comment]
发自我的iPhone

**Comment by potpot3** [comment]
哦？是找到了代码了吗？不过没有看到附件耶

**Comment by zyl0462** [comment]
一会再发下，看看

发自我的iPhone

**Comment by zyl0462** [comment]
留个邮箱吧，之前的回复都是邮箱回复的，挂的附件这里看不到。

**Comment by potpot3** [comment]
potki@sohu.com

**Comment by potpot3** [comment]
麻烦你了～
